name: Build

on:
  push:
    branches: [main]
  workflow_call:
    inputs:
      ref:
        description: Git ref to build (branch or tag)
        required: false
        default: ${{ github.ref }}
        type: string
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
      max-parallel: 1

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry & deps
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-in-project: true

      - name: Install dependencies
        shell: bash
        run: |
          poetry config virtualenvs.in-project true
          poetry install --with dev

      - name: Build executable with PyInstaller
        shell: bash
        run: |
          poetry run pyinstaller main.py \
            --onefile \
            --name remesh-${{ matrix.os }} \
            --exclude-module matplotlib \
            --exclude-module mpl_toolkits

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: remesh-${{ matrix.os }}
          path: dist/remesh-${{ matrix.os }}*
