name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        ext: ["", ".exe", ""]
      max-parallel: 1
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry & deps
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --with dev

      - name: Build with PyInstaller
        run: |
          poetry run pyinstaller main.py \
            --onefile \
            --name remesh-${{ matrix.os }} \
            --exclude-module matplotlib \
            --exclude-module mpl_toolkits

      - name: Rename for extension
        if: matrix.ext != ''
        run: |
          mv dist/remesh-${{ matrix.os }} dist/remesh-${{ matrix.os }}${{ matrix.ext }}

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: remesh-${{ matrix.os }}${{ matrix.ext }}
          path: dist/remesh-${{ matrix.os }}${{ matrix.ext }}
