name: Build & Publish Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-artifacts:
    uses: ./.github/workflows/build.yaml
    with:
      ref: ${{ github.event.release.tag_name }}

  publish:
    needs: build-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Flatten artifacts
        run: |
          mkdir -p flat
          for d in dist/*; do
            cp "$d"/* flat/
          done

      - name: Attach binaries to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: flat/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
