name: Build & Publish Release

on:
  release:
    types: [created]

jobs:
  build-artifacts:
    uses: ./.github/workflows/build.yaml
    with:
      ref: ${{ github.event.release.tag_name }}

  publish:
    needs: build-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Attach binaries to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/remesh-ubuntu-latest
            dist/remesh-windows-latest.exe
            dist/remesh-macos-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
