# .github/workflows/publish.yml
name: Publish Release

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  publish:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      contains(github.event.workflow_run.head_commit.message, 'Release')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts from Build
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Attach binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/remesh-ubuntu-latest
            dist/remesh-windows-latest.exe
            dist/remesh-macos-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
